site_name: TIM CS203A Notes
theme: readthedocs
markdown_extensions:
  - admonition
nav:
  - 首頁: index.md
  - 課程記錄:  
    - 動態記憶體: notes/dynamic.md
    - 鏈結串列: notes/linklist.md
    - 陣列(Array): notes/array.md
    - 堆疊vs佇列: notes/stackqueue.md    
    - 雜湊表: notes/hashtable.md
  - 作業: 
    - Assignment1: homework.md